### ISSUE TITLE
Replace JodaTime with new Java time API (Java 8) and JSR-310 backport (Java 6 and 7)

### ISSUE THREAD

**Issue by sidorovis** [atdl4j/atdl4j#21]
At https://github.com/atdl4j/atdl4j/blob/master/pom.xml

We have:
<dependency>
    <groupId>joda-time<\/groupId>
    <artifactId>joda-time<\/artifactId>
    <version>1.6<\/version>
<\/dependency>

Could we simply change version of joda-time to 2.1 ?

**Comment by TyAshley** [comment]
This has been corrected with the 4.0.0 release. The project has been updated to Java 1.8 and vulnerabilities have been addressed (JodaTime, Log4j, etc)
