### ISSUE TITLE
Exception when using Strat and End Time

### ISSUE THREAD

**Issue by chirazAmara** [atdl4j/atdl4j#23]
This exception occurs despite the values are set and shown correctly. This is the stack trace.
theEnd parameter is not returned in the GetAtdlProperties
Parameter "End" ("End")  is required.  Rule tested: [null EX]

org.atdl4j.data.exception.ValidationException: Parameter "End" ("End")  is required.  Rule tested: [null EX]
    at org.atdl4j.data.StrategyRuleset.buildValidationException(StrategyRuleset.java:157)
    at org.atdl4j.data.StrategyRuleset.validate(StrategyRuleset.java:78)
    at org.atdl4j.ui.impl.AbstractStrategyUI.validate(AbstractStrategyUI.java:580)
    at org.atdl4j.ui.app.impl.AbstractAtdl4jCompositePanel.getSelectedStrategyDetails(AbstractAtdl4jCompositePanel.java:253)

**Comment by rob3rtb** [comment]
@chirazAmara : Isn't this due to a validation rule in your ATDL file ? It looks like the parameter "End" 
is flagged as required ( *use="required"* ).
If not, please  attach the ATDL file to this ticket

**Comment by chirazAmara** [comment]
Yes - this parameter is flagged as required! however, the value is inserted in the date spinner, in the code it's null

**Comment by chirazAmara** [comment]
any update please?

**Comment by johnnyshields** [comment]
@chirazAmara this is an open source project. Can you please investigate the issue and fix it yourself, then raise a pull request?

**Comment by scottatwell** [comment]
I would recommend that you review slide 33 of https://www.fixtrading.org/packages/implementing-fixatdl-technical/ (link is available within atdl4j's wiki.  Specifically, one typically wants to designate a checkbox or radio buttons to control the enabled (eg nullable) state of the Control.  This allows one to handle the fact that the control itself is always-drawn/populated with something, even in cases where the user has not specified a value they want to use.
![Implementing FIXatdl - Common Issue Clock control's Parameter is optional](https://user-images.githubusercontent.com/184692/232890425-6ee7fdd6-102f-47ae-91a5-01f42b15abb9.png)
