### ISSUE TITLE
Cannot compile source code atdl4j 3.0.3

### ISSUE THREAD

**Issue by hagerMhadhbi** [atdl4j/atdl4j#25]
I need to compile the project atdl4j 3.0.3 in order to debug some issues but still with errors:

* The return type is incompatible with AbstractTypeConverter<Comparable<DateTime>>.convertParameterValueToControlValue(Object)

* The method setValue(Comparable<DateTime>) in the type SWTClockWidget is not applicable for the arguments (DateTime)

* Cannot cast from Comparable<DateTime> to DateTime

Are there any dependencies please?? 

Or we just need to remove this "Comparable<DateTime>" ?
If yes - please update the source code with necessary changes.

**Comment by scottatwell** [comment]
The DateTime class is part of Joda Time (org.joda.time.DateTime). In my environment (joda-time-2.3.jar), DateTime extends a base class (AbstractInstant) that implements ReadableInstant which implements Comparable<ReadableInstant>.

Scott

**Comment by hagerMhadhbi** [comment]
I have updated the joda-time jar to 2.3 but have the same issue :(
My dependencies are:
* atdl4j-3.0.3.jar
* jide-common.jar
* log4j-1.2.15.jar
* swt.jar
* jide-oss-3.5.15.jar
* joda-time-2.3.jar

Is there any missing one please??

**Comment by hagerMhadhbi** [comment]
Problem resolved: need the joda-time 1.6
